default: &default
  adapter: postgresql
  encoding: utf8
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: optolead_development

test:
  <<: *default
  database: optolead_test

production:
  <<: *default
  database: optolead_production
  username: optolead
  password: <%= ENV['STOCKNOTES_DATABASE_PASSWORD'] %>
